# Generated by Django 3.2.9 on 2021-12-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('water', 'water'), ('woodland', 'woodland'), ('mountain', 'mountain'), ('plain', 'plain')], max_length=10)),
                ('development', models.CharField(choices=[('wilds', 'wilds'), ('undev', 'undev'), ('rural', 'rural'), ('suburbs', 'suburbs'), ('semiurban', 'semiurban'), ('urban', 'urban'), ('metropolis', 'metropolis')], max_length=10)),
                ('rich_soil', models.BooleanField(default=False, max_length=10)),
                ('rich_coal', models.BooleanField(default=False, max_length=10)),
                ('rich_oilfield', models.BooleanField(default=False, max_length=10)),
                ('rich_uranium', models.BooleanField(default=False, max_length=10)),
                ('rich_rareearth', models.BooleanField(default=False, max_length=10)),
                ('rich_metals', models.BooleanField(default=False, max_length=10)),
            ],
        ),
    ]
